# Generated by Django 3.2.9 on 2022-01-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsnsac',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='salestaxrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='stockunit',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
