# Generated by Django 3.2.9 on 2022-02-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
