# Generated by Django 3.2.9 on 2022-02-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_is_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
